DROP TABLE IF EXISTS
award_vote,
award_reference,
award_judge,
award_emailtemplate,
award_emaillog,
award_email,
award_cyclewinner,
award_cyclelog,
award_reason,
award_document,
award_nomination,
award_participant_hash,
award_participant,
award_invitation,
award_badge,
award_cycle,
award_award;